"""Type stubs for MLX Python wrapper."""
from typing import Any, Tuple


class Mlx:
    """MLX Python wrapper for Mlx C library."""

    def __init__(self) -> None: ...
    def mlx_init(self) -> Any: ...
    def mlx_release(self, mlx_ptr: Any) -> int: ...

    def mlx_new_window(self, mlx_ptr: Any,
                       width: int,
                       height: int,
                       title: str) -> Any: ...

    def mlx_clear_window(self, mlx_ptr: Any, win_ptr: Any) -> int: ...

    def mlx_pixel_put(self, mlx_ptr: Any,
                      win_ptr: Any,
                      x: int,
                      y: int,
                      color: int) -> int: ...

    def mlx_destroy_window(self, mlx_ptr: Any, win_ptr: Any) -> int: ...
    def mlx_destroy_image(self, mlx_ptr: Any, img: Any) -> int: ...
    def mlx_new_image(self, mlx_ptr: Any, width: int, height: int) -> Any: ...

    def mlx_get_data_addr(self,
                          img: Any) -> Tuple[memoryview, int, int, int]: ...

    def mlx_hook(self, win_ptr: Any,
                 x_event: int,
                 x_mask: int, funct: Any, param: Any) -> int: ...

    def mlx_key_hook(self, win_ptr: Any, funct: Any, param: Any) -> int: ...
    def mlx_loop(self, mlx_ptr: Any) -> int: ...
    def mlx_loop_exit(self, mlx_ptr: Any) -> None: ...

    def mlx_put_image_to_window(self, mlx_ptr: Any,
                                win_ptr: Any,
                                img: Any,
                                x: int,
                                y: int) -> int: ...
